/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;


import Backend.TrainerRole;
import Backend.Member;
import Backend.MemberDatabase;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mirol
 */
public class ViewMemberWindow extends javax.swing.JFrame {
       private TrainerRole trainer;
    private MemberDatabase database;
    private final String [] columnsNames = null;
    
     public ViewMemberWindow(TrainerRole trainer,MemberDatabase database) {
        initComponents();
        this.trainer=trainer;
        this.database=database;
        String [] columnsNames={"ID", "Name", "Email","Membership Type","PhoneNumber"};
        ArrayList<Member> members =trainer.getListOfMembers();
        Object[][]data =new Object[members.size()][columnsNames.length]; 
        for (int i=0;i<members.size();i++){
             Member member=members.get(i);
             data[i]=member.lineRepresesntation().split(",");}
//        DefaultTableModel model =new DefaultTableModel(data,columnsNames);
//        JTable table =new JTable(model);
           setData(data);
          this.setVisible(false);
    }
    public void setData(Object [][] data)
    {
        jTable1.setModel(new DefaultTableModel(data,columnsNames)
                {
                  @Override
                  public boolean isCellEditable(int row,int column)
                {
                    return false;
                }
                });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
